# Generated by Django 2.2.5 on 2022-01-26 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
    ]
