# Generated by Django 2.2.5 on 2022-01-26 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220126_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'managed': False},
        ),
    ]
