# Generated by Django 2.2.5 on 2022-01-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='member',
        ),
    ]
