# Generated by Django 2.2.5 on 2022-01-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
